name: bharath_s_application14
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.6
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0 # Downgraded to version 0.17.0 to match firebase_auth
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/ComfortaaSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ComfortaaRegular.ttf
          weight: 400
        - asset: assets/fonts/ComfortaaMedium.ttf
          weight: 500
        - asset: assets/fonts/ComfortaaBold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Karla
      fonts:
        - asset: assets/fonts/KarlaRegular.ttf
          weight: 400
